apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ricc-custom-targets-pipeline # was custom-targets-pipeline
serialPipeline:
  stages:
  - targetId: sample-env
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: sample-env
customTarget:
  customTargetType: ricc-basic-custom-target
---

apiVersion: deploy.cloud.google.com/v1
kind: CustomTargetType
metadata:
  name: ricc-basic-custom-target
customActions:
  renderAction: ricc-custom-render
  deployAction: ricc-custom-deploy
