apiVersion: skaffold/v4beta7
kind: Config
customActions:
- name: ricc-custom-render
  containers:
  - name: render
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:66e2681aa3099b4e517e4cdcdefff8f2aa45d305007124ccdc09686f6712d018
    command: ['/bin/bash']
    args:
      - '-c'
      # This goes in the rendered manifest of the Release. Eg, https://pantheon.corp.google.com/deploy/delivery-pipelines/us-central1/ricc-custom-targets-pipeline/release-inspector;releaseId=test-release-002;targetId=sample-env;phaseId=stable;mode=manifest?e=-13802955&mods=logs_tg_staging&project=rick-and-nardy-demo
      - |-
        echo "🇮🇹 Welcome to a sample 🤌 Italian manifest rendered content" > manifest.txt
        gsutil cp manifest.txt $CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt
        echo {\"resultStatus\": \"SUCCEEDED\", \"manifestFile\": \"$CLOUD_DEPLOY_OUTPUT_GCS_PATH/manifest.txt\"} > results.json
        gsutil cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
- name: ricc-custom-deploy
  containers:
  - name: deploy
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:66e2681aa3099b4e517e4cdcdefff8f2aa45d305007124ccdc09686f6712d018
    command: ['/bin/bash']
    args:
      - '-c'
      - |-
        echo {\"resultStatus\": \"SUCCEEDED\"} > results.json
        gsutil cp results.json $CLOUD_DEPLOY_OUTPUT_GCS_PATH/results.json
