# Copied from https://github.com/GoogleCloudPlatform/cloud-deploy-samples/blob/main/custom-targets/vertex-ai/quickstart/

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  # [ricc] **BEWARE** This needs to be THE SAME as ${VAI_PIPELINE}
  # .. but I dont want to configure yet another config thingy.
  # VAI_PIPELINE: vertex-ai-cloud-deploy-pipeline
  #name: vertex-ai-demo-v2
  #name: vertex-ai-cloud-deploy-pipeline
  name: vertex-triptych
serialPipeline:
  stages:
  - targetId: dev-endpoint
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"] # TODO change me
  - targetId: preprod-endpoint
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"] # TODO change me
  - targetId: prod-endpoint
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"] # This is correct (PROD)
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-dev
  customTarget/vertexAIConfigurationPath: "dev/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "1"
  customTarget/vertexAIAliases: "demo24-dev,testme,stage1"
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: preprod-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-prod
  customTarget/vertexAIConfigurationPath: "preprod/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "demo24-preprod,nearlythere,stage2"
  # Note: the customTarget/vertexAIModel is passed via CLI instead..
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-prod
  customTarget/vertexAIConfigurationPath: "prod/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "demo24-prod,champion,stage3"
  # Note: the customTarget/vertexAIModel is passed via CLI instead..
