# Copied from https://github.com/GoogleCloudPlatform/cloud-deploy-samples/blob/main/custom-targets/vertex-ai/quickstart/

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  # [ricc] **BEWARE** This needs to be THE SAME as ${VAI_PIPELINE}
  # .. but I dont want to configure yet another config thingy.
  # VAI_PIPELINE: vertex-ai-cloud-deploy-pipeline
  #name: vertex-ai-demo-v2
  #name: vertex-ai-cloud-deploy-pipeline
  name: vertex-demo-verify # v4 after tryptich :)
serialPipeline:
  stages:
  - targetId: vertex-dev
    strategy:
      standard:
        # Verification for DEV
        verify: true
        postdeploy:
          actions: ["add-aliases"] # TODO change me
  - targetId: vertex-preprod
    strategy:
      standard:
        verify: true
        postdeploy:
          actions: ["add-aliases"] # TODO change me
  - targetId: vertex-prod
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"] # This is correct (PROD)
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: vertex-dev
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-dev
  customTarget/vertexAIConfigurationPath: "dev/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "1"
  customTarget/vertexAIAliases: "demo24-dev,v4-verify,put-on-water,stage1"
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: vertex-preprod
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-preprod
  customTarget/vertexAIConfigurationPath: "preprod/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "demo24-preprod,v4-verify,butta-la-pasta,stage2"
  # Note: the customTarget/vertexAIModel is passed via CLI instead..
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: vertex-prod
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: projects/rick-and-nardy-demo/locations/us-central1/endpoints/demo24-prod
  customTarget/vertexAIConfigurationPath: "prod/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "demo24-prod,v4-verify,pasta-ready,stage3"
  # Note: the customTarget/vertexAIModel is passed via CLI instead..
