########################################################
# This is a sample from auto_import_config.py v1.1
# Code: https://github.com/palladius/sakura/blob/master/bin/auto_import_config.py
########################################################
# Once done you can do: gcloud config configurations activate YOUR_VAVORITE_CONFIG
local_config:
  auto: true
configurations:
  # default:
  #   project: my-default-personal-project
  #   compute/region: us-central1
  #   compute/zone: us-central1-b
  #   account: your.personal.email@gmail.com
  # # Note: gcloud wont accept this config name if it starts with a number (#btdt)
  d240308-nikita-prediction:
    gcloud:
      project: rick-and-nardy-demo
      compute/region: us-central1
      compute/zone: us-central1-b
      account: ricc@google.com
    env:
      BUCKET_NAME: "${PROJECT_ID}-flower-bucket"
      GS_BUCKET: "gs://${BUCKET_NAME}"
      OUTPUT_MODEL_DIRECTORY: "gs://${BUCKET_NAME}/flowers_output/"
      OUTPUT_MODEL_DIRECTORY_V3: "gs://${BUCKET_NAME}/model_output/"
      VERTEX_TRAINING_JOB_NAME: 'flowers-try3'
      REPO_NAME: 'my-awesome-app'
      # Not implemented yet, but who knows..
      IMAGE_URI: "${GCP_REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/flower_image_try3:latest"
